### Лабораторная работа № 4

In [1]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, max_error
from sklearn.metrics import confusion_matrix, classification_report
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
import numpy as np
import pandas as pd

### Загрузка данных и разделение на выборки

In [7]:
# Регрессия
df = pd.read_csv("../data/regression/trip_duration_update.csv", index_col=0)
display(df)

y = df["trip_duration"]
X = df.drop(["trip_duration"], axis=1)

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X, y, test_size=0.2)

# Классификация

df = pd.read_csv("../data/classification/csgo_task_update.csv", index_col=0).drop_duplicates()
display(df)

y = df['bomb_planted']
X = df.drop(['bomb_planted'], axis=1)

underSampler = RandomUnderSampler(sampling_strategy='majority')
X_under_sample, y_under_sample = underSampler.fit_resample(X, y)

X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X_under_sample, y_under_sample, test_size=0.2, random_state = 4)

scaler = StandardScaler()

scaler.fit(X_train_clf, y_train_clf)
X_train_std_clf = scaler.transform(X_train_clf)
X_test_std_clf = scaler.transform(X_test_clf)


pickup_longitude  pickup_latitude  dropoff_longitude  \
0             -73.953918        40.778873         -73.963875   
1             -73.988312        40.731743         -73.994751   
2             -73.997314        40.721458         -73.948029   
3             -73.961670        40.759720         -73.956779   
4             -74.017120        40.708469         -73.988182   
...                  ...              ...                ...   
149995        -73.980270        40.775326         -73.962090   
149996        -73.981804        40.769016         -73.979767   
149997        -73.989838        40.714241         -73.988083   
149998        -73.989395        40.726200         -74.001060   
149999        -73.961037        40.777695         -73.967461   

        dropoff_latitude  trip_duration  
0              40.771164            400  
1              40.694931           1100  
2              40.774918           1635  
3              40.780628           1141  
4              40.740631            848  
...                  ...            ...  
149995         40.763794            690  
149996         40.780998            753  
149997         40.745743            804  
149998         40.721779            599  
149999         40.801250            429  

[150000 rows x 5 columns]

time_left  ct_score  t_score  bomb_planted  ct_health  t_health  \
0          175.00       0.0      0.0             0      500.0     500.0   
1          156.03       0.0      0.0             0      500.0     500.0   
2           96.03       0.0      0.0             0      391.0     400.0   
3           76.03       0.0      0.0             0      391.0     400.0   
4          174.97       1.0      0.0             0      500.0     500.0   
...           ...       ...      ...           ...        ...       ...   
122405      15.41      11.0     14.0             1      200.0     242.0   
122406     174.93      11.0     15.0             0      500.0     500.0   
122407     114.93      11.0     15.0             0      500.0     500.0   
122408      94.93      11.0     15.0             0      500.0     500.0   
122409      74.93      11.0     15.0             0      375.0     479.0   

        ct_money  t_money  ct_players_alive  t_players_alive  map_de_cache  \
0         4000.0   4000.0               5.0              5.0             0   
1          600.0    650.0               5.0              5.0             0   
2          750.0    500.0               4.0              4.0             0   
3          750.0    500.0               4.0              4.0             0   
4        18350.0  10750.0               5.0              5.0             0   
...          ...      ...               ...              ...           ...   
122405     100.0   5950.0               2.0              4.0             0   
122406   11500.0  23900.0               5.0              5.0             0   
122407    1200.0   6700.0               5.0              5.0             0   
122408    1200.0   6700.0               5.0              5.0             0   
122409    1100.0   7000.0               4.0              5.0             0   

        map_de_dust2  map_de_inferno  map_de_mirage  map_de_nuke  \
0                  1               0              0            0   
1                  1               0              0            0   
2                  1               0              0            0   
3                  1               0              0            0   
4                  1               0              0            0   
...              ...             ...            ...          ...   
122405             0               0              0            0   
122406             0               0              0            0   
122407             0               0              0            0   
122408             0               0              0            0   
122409             0               0              0            0   

        map_de_overpass  map_de_train  map_de_vertigo  
0                     0             0               0  
1                     0             0               0  
2                     0             0               0  
3                     0             0               0  
4                     0             0               0  
...                 ...           ...             ...  
122405                0             1               0  
122406                0             1               0  
122407                0             1               0  
122408                0             1               0  
122409                0             1               0  

[116579 rows x 18 columns]

## Регрессия

### Без гиперпараметров

In [6]:
model_regression = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(4,)),
        tf.keras.layers.Dense(256, activation="relu"),
        tf.keras.layers.Dense(512, activation="relu"),
        tf.keras.layers.Dropout(0.3),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dropout(0.01),
        tf.keras.layers.Dense(1, activation="linear")
    ]
)

In [7]:
model_regression.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               1280      
                                                                 
 dense_1 (Dense)             (None, 512)               131584    
                                                                 
 dropout (Dropout)           (None, 512)               0         
                                                                 
 dense_2 (Dense)             (None, 128)               65664     
                                                                 
 dropout_1 (Dropout)         (None, 128)               0         
                                                                 
 dense_3 (Dense)             (None, 64)                8256      
                                                                 
 dropout_2 (Dropout)         (None, 64)                0

In [8]:
model_regression.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="mae")

In [9]:
model_regression.fit(X_train_reg, y_train_reg, epochs=15)

Epoch 1/15
3750/3750 [==============================] - 17s 4ms/step - loss: 582.2136
Epoch 2/15
3750/3750 [==============================] - 13s 4ms/step - loss: 580.0770
Epoch 3/15
3750/3750 [==============================] - 16s 4ms/step - loss: 578.6780
Epoch 4/15
3750/3750 [==============================] - 17s 4ms/step - loss: 577.8632
Epoch 5/15
3750/3750 [==============================] - 19s 5ms/step - loss: 578.0928
Epoch 6/15
3750/3750 [==============================] - 15s 4ms/step - loss: 578.1614
Epoch 7/15
3750/3750 [==============================] - 14s 4ms/step - loss: 577.7893
Epoch 8/15
3750/3750 [==============================] - 14s 4ms/step - loss: 575.5150
Epoch 9/15
3750/3750 [==============================] - 15s 4ms/step - loss: 574.5679
Epoch 10/15
3750/3750 [==============================] - 16s 4ms/step - loss: 574.2354
Epoch 11/15
3750/3750 [==============================] - 16s 4ms/step - loss: 574.0769
Epoch 12/15
3750/3750 [=============================

In [10]:
y_pred_reg = model_regression.predict(X_test_reg)

938/938 [==============================] - 2s 2ms/step


In [11]:
print(mean_absolute_error(y_test_reg, y_pred_reg))
print(mean_squared_error(y_test_reg, y_pred_reg))
print(r2_score(y_test_reg, y_pred_reg))
print(max_error(y_test_reg, y_pred_reg))

545.2739791015625
9203871.36311879
-0.010086439561509897
85734.08569335938


### Классификация

In [12]:
model_classification = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(17,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dense(256, activation="relu"),
        tf.keras.layers.Dense(1024, activation="tanh"),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(512, activation="tanh"),
        tf.keras.layers.Dropout(0.01),
        tf.keras.layers.Dense(128, activation="tanh"),
        tf.keras.layers.Dense(64, activation="tanh"),
        tf.keras.layers.Dense(32, activation="tanh"),
        tf.keras.layers.Dense(16, activation="tanh"),
        tf.keras.layers.Dense(1, activation="sigmoid")
    ]
)

In [13]:
model_classification.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 128)               2304      
                                                                 
 dense_6 (Dense)             (None, 256)               33024     
                                                                 
 dense_7 (Dense)             (None, 1024)              263168    
                                                                 
 dropout_3 (Dropout)         (None, 1024)              0         
                                                                 
 dense_8 (Dense)             (None, 512)               524800    
                                                                 
 dropout_4 (Dropout)         (None, 512)               0         
                                                                 
 dense_9 (Dense)             (None, 128)              

In [14]:
model_classification.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.00001), loss="binary_crossentropy")

In [15]:
model_classification.fit(X_train_std_clf, y_train_clf, epochs=15)

Epoch 1/15
685/685 [==============================] - 14s 16ms/step - loss: 0.3244
Epoch 2/15
685/685 [==============================] - 11s 16ms/step - loss: 0.2303
Epoch 3/15
685/685 [==============================] - 10s 15ms/step - loss: 0.2053
Epoch 4/15
685/685 [==============================] - 10s 15ms/step - loss: 0.1918
Epoch 5/15
685/685 [==============================] - 10s 15ms/step - loss: 0.1851
Epoch 6/15
685/685 [==============================] - 10s 15ms/step - loss: 0.1790
Epoch 7/15
685/685 [==============================] - 10s 15ms/step - loss: 0.1748
Epoch 8/15
685/685 [==============================] - 10s 15ms/step - loss: 0.1716
Epoch 9/15
685/685 [==============================] - 11s 16ms/step - loss: 0.1696
Epoch 10/15
685/685 [==============================] - 10s 15ms/step - loss: 0.1676
Epoch 11/15
685/685 [==============================] - 10s 15ms/step - loss: 0.1653
Epoch 12/15
685/685 [==============================] - 10s 15ms/step - loss: 0.1630
E

In [16]:
model_classification.predict(X_test_std_clf, verbose=None)[:5]

array([[0.01426115],
       [0.01368352],
       [0.9522381 ],
       [0.01376656],
       [0.01375258]], dtype=float32)

In [17]:
y_pred = np.around(model_classification.predict(X_test_std_clf, verbose=None))
print(classification_report(y_test_clf, y_pred))
print(confusion_matrix(y_test_clf, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.89      0.94      2784
           1       0.90      0.99      0.94      2690

    accuracy                           0.94      5474
   macro avg       0.94      0.94      0.94      5474
weighted avg       0.94      0.94      0.94      5474

[[2481  303]
 [  35 2655]]


### Реализация персептрона

In [2]:
class Activation:
    def callFunction(x):
        pass
    def callDerivative(x):
        pass

class Relu(Activation):
    @staticmethod
    def callFunction(x):
        return np.maximum(0,x)
    @staticmethod
    def callDerivative(x):
        return np.where(x > 0, 1.0, 0.0)

class Sigmoid(Activation):
    @staticmethod
    def callFunction(x):
        return 1 / (1 + np.exp(-x))
    @staticmethod
    def callDerivative(x):
        return Sigmoid.callFunction(x) * (1- Sigmoid.callFunction(x))
class TangH(Activation):
    
    @staticmethod
    def callFunction( x):
        return (np.exp(x) - np.exp(-x)) / (np.exp(x)+np.exp(-x))
    
    @staticmethod
    def callDerivative(x):
        return 1 - TangH.callFunction(x) ** 2



In [3]:
class Layer:
    def __init__(self):
        self.input = None
        self.output = None
    
    def forward_propagation(self, input):
        raise NotImplementedError

    def backward_propagation(self, output_error):
        raise NotImplementedError
    
class FCLayer(Layer):

    def __init__(self, input_size, output_size):
        self.weights = np.random.rand(input_size, output_size) - 0.5
        self.bias = np.random.rand(1, output_size) - 0.5

    def forward_propagation(self, input_data):
        self.input = input_data
        self.output = np.dot(self.input, self.weights) + self.bias
        return self.output

    def backward_propagation(self, output_error, learning_rate):
        input_error = np.dot(output_error, self.weights.T)#dE/dx
        weights_error = np.dot(self.input.T, output_error)#dE/dw
        self.weights -= learning_rate * weights_error
        self.bias -= learning_rate * output_error
        return input_error #dE/dB так как равен de/dx

class ActivationLayer(Layer):
    def __init__(self, activation, activation_prime):
        self.activation = activation
        self.activation_prime = activation_prime

    def forward_propagation(self, input_data):
        self.input = input_data
        self.output = self.activation(self.input)
        return self.output

    def backward_propagation(self, output_error, learning_rate):
        return self.activation_prime(self.input) * output_error


In [45]:
class LossFunction:
    def fun():
        pass
    def derivative():
        pass

class MeanSquaredError(LossFunction):
    def fun(y_true, y_pred):
        return np.mean(np.power(y_true-y_pred, 2))
    
    def derivative(y_true, y_pred):
        return 2*(y_pred-y_true)/y_true.size


In [50]:
class NN:
    def __init__(self):
        self.layers = []
        self.loss = None
        self.loss_prime = None

    def add(self, layer):
        self.layers.append(layer)

    def compile(self, loss, loss_prime):
        self.loss = loss
        self.loss_prime = loss_prime

    def predict(self, input_data):
        samples = len(input_data)
        result = []

        for i in range(samples):
            output = input_data[i]
            for layer in self.layers:
                output = layer.forward_propagation(output)
            result.append(*output)

        return result

    def fit(self, x_train, y_train, epochs, learning_rate):

        samples = len(x_train)

        for i in range(epochs):

            for j in range(samples):
                output = x_train[j]
                for layer in self.layers:
                    output = layer.forward_propagation(output)

                error = self.loss_prime(y_train[j], output)
                for layer in reversed(self.layers):
                    error = layer.backward_propagation(error, learning_rate)
                    
            

### Классификация

In [31]:
df = pd.read_csv("../data/classification/csgo_task_update.csv", index_col=0).drop_duplicates()
df

time_left  ct_score  t_score  bomb_planted  ct_health  t_health  \
0          175.00       0.0      0.0             0      500.0     500.0   
1          156.03       0.0      0.0             0      500.0     500.0   
2           96.03       0.0      0.0             0      391.0     400.0   
3           76.03       0.0      0.0             0      391.0     400.0   
4          174.97       1.0      0.0             0      500.0     500.0   
...           ...       ...      ...           ...        ...       ...   
122405      15.41      11.0     14.0             1      200.0     242.0   
122406     174.93      11.0     15.0             0      500.0     500.0   
122407     114.93      11.0     15.0             0      500.0     500.0   
122408      94.93      11.0     15.0             0      500.0     500.0   
122409      74.93      11.0     15.0             0      375.0     479.0   

        ct_money  t_money  ct_players_alive  t_players_alive  map_de_cache  \
0         4000.0   4000.0               5.0              5.0             0   
1          600.0    650.0               5.0              5.0             0   
2          750.0    500.0               4.0              4.0             0   
3          750.0    500.0               4.0              4.0             0   
4        18350.0  10750.0               5.0              5.0             0   
...          ...      ...               ...              ...           ...   
122405     100.0   5950.0               2.0              4.0             0   
122406   11500.0  23900.0               5.0              5.0             0   
122407    1200.0   6700.0               5.0              5.0             0   
122408    1200.0   6700.0               5.0              5.0             0   
122409    1100.0   7000.0               4.0              5.0             0   

        map_de_dust2  map_de_inferno  map_de_mirage  map_de_nuke  \
0                  1               0              0            0   
1                  1               0              0            0   
2                  1               0              0            0   
3                  1               0              0            0   
4                  1               0              0            0   
...              ...             ...            ...          ...   
122405             0               0              0            0   
122406             0               0              0            0   
122407             0               0              0            0   
122408             0               0              0            0   
122409             0               0              0            0   

        map_de_overpass  map_de_train  map_de_vertigo  
0                     0             0               0  
1                     0             0               0  
2                     0             0               0  
3                     0             0               0  
4                     0             0               0  
...                 ...           ...             ...  
122405                0             1               0  
122406                0             1               0  
122407                0             1               0  
122408                0             1               0  
122409                0             1               0  

[116579 rows x 18 columns]

In [33]:
X_clf = df.drop(["bomb_planted"], axis=1).values
y_clf = df["bomb_planted"].values

In [34]:
std = StandardScaler()
std.fit(X_clf)
X_clf = pd.DataFrame(std.transform(X_clf), columns=df.drop(["bomb_planted"], axis=1).columns).values

In [38]:
underSampler = RandomUnderSampler(random_state=42)
X_clf, y_clf = underSampler.fit_resample(X_clf,y_clf)
X_clf= X_clf.reshape(X_clf.shape[0], 1, X_clf.shape[1])

In [39]:
X_clf_train, X_clf_test, y_clf_train, y_clf_test = train_test_split(X_clf,
                                                                        y_clf,
                                                                        stratify=y_clf,
                                                                        test_size=0.2)

In [51]:
model_classification = NN()
model_classification.add(FCLayer(17, 3))
model_classification.add(ActivationLayer(TangH.callFunction, TangH.callDerivative))
model_classification.add(FCLayer(3, 1))
model_classification.add(ActivationLayer(Sigmoid.callFunction, Sigmoid.callDerivative))
model_classification.compile(MeanSquaredError.fun, MeanSquaredError.derivative)
model_classification.fit(X_clf_train, y_clf_train, epochs=50, learning_rate=0.001)
pred_classification = model_classification.predict(X_clf_test)

In [43]:
pred_classification

[array([0.7911412]),
 array([0.0009277]),
 array([0.84662934]),
 array([0.00070062]),
 array([0.00664607]),
 array([0.00257202]),
 array([0.97717037]),
 array([0.69560569]),
 array([0.97710683]),
 array([0.00076744]),
 array([0.920311]),
 array([0.00351359]),
 array([0.00066971]),
 array([0.98863993]),
 array([0.52106529]),
 array([0.00304674]),
 array([0.00070873]),
 array([0.96904064]),
 array([0.9295813]),
 array([0.94973091]),
 array([0.03580503]),
 array([0.6369757]),
 array([0.00075252]),
 array([0.87552096]),
 array([0.00143142]),
 array([0.70912659]),
 array([0.00070667]),
 array([0.96924453]),
 array([0.97342003]),
 array([0.00081644]),
 array([0.00067278]),
 array([0.75090026]),
 array([0.94543034]),
 array([0.00094043]),
 array([0.00082681]),
 array([0.00068014]),
 array([0.00373635]),
 array([0.00237275]),
 array([0.48197526]),
 array([0.97884303]),
 array([0.00078371]),
 array([0.95594822]),
 array([0.98050621]),
 array([0.01341286]),
 array([0.0010739]),
 array([0.8965596

In [44]:
print(classification_report(y_clf_test, np.around(pred_classification)))
print(confusion_matrix(y_clf_test, np.around(pred_classification)))

              precision    recall  f1-score   support

           0       0.99      0.89      0.94      2737
           1       0.90      0.99      0.94      2737

    accuracy                           0.94      5474
   macro avg       0.95      0.94      0.94      5474
weighted avg       0.95      0.94      0.94      5474

[[2448  289]
 [  27 2710]]


### Регрессия

In [46]:
df_reg = pd.read_csv("../data/regression/trip_duration_update.csv", index_col=0).drop_duplicates()
df_reg

pickup_longitude  pickup_latitude  dropoff_longitude  \
0             -73.953918        40.778873         -73.963875   
1             -73.988312        40.731743         -73.994751   
2             -73.997314        40.721458         -73.948029   
3             -73.961670        40.759720         -73.956779   
4             -74.017120        40.708469         -73.988182   
...                  ...              ...                ...   
149995        -73.980270        40.775326         -73.962090   
149996        -73.981804        40.769016         -73.979767   
149997        -73.989838        40.714241         -73.988083   
149998        -73.989395        40.726200         -74.001060   
149999        -73.961037        40.777695         -73.967461   

        dropoff_latitude  trip_duration  
0              40.771164            400  
1              40.694931           1100  
2              40.774918           1635  
3              40.780628           1141  
4              40.740631            848  
...                  ...            ...  
149995         40.763794            690  
149996         40.780998            753  
149997         40.745743            804  
149998         40.721779            599  
149999         40.801250            429  

[150000 rows x 5 columns]

In [47]:
y_reg = df_reg["trip_duration"].values
X_reg = df_reg.drop(["trip_duration"], axis=1).values.reshape(df_reg.shape[0], 1, df_reg.shape[1] - 1)

In [48]:
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.2,random_state=4)
X_train_reg.shape, X_test_reg.shape, y_train_reg.shape, y_test_reg.shape 

((120000, 1, 4), (30000, 1, 4), (120000,), (30000,))

In [52]:
model_reg = NN()
model_reg.add(FCLayer(4, 16))
model_reg.add(ActivationLayer(Relu.callFunction, Relu.callFunction))
model_reg.add(FCLayer(16, 8))
model_reg.add(ActivationLayer(Relu.callFunction, Relu.callFunction))
model_reg.add(FCLayer(8, 4))
model_reg.add(ActivationLayer(Relu.callFunction, Relu.callFunction))
model_reg.add(FCLayer(4, 1))
model_reg.compile(MeanSquaredError.fun, MeanSquaredError.derivative)
model_reg.fit(X_train_reg, y_train_reg, epochs=50, learning_rate=0.001)


In [56]:
pred_reg = model_reg.predict(X_test_reg)

In [55]:
print(mean_absolute_error(y_test_reg, pred_reg))
print(mean_squared_error(y_test_reg, pred_reg))
print(r2_score(y_test_reg, pred_reg))
print(max_error(y_test_reg, pred_reg))

603.3592851045591
7647462.8936026925
-0.0007143003156109273
85363.35361232058
